import {
  Box,
  Container,
  Divider,
  Heading,
  Image,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import React from "react";
import Navbar from "../navbar";
type LayoutProps = {
  children: React.ReactNode;
};

const index: React.FunctionComponent<LayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>EM-DevTTer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.svg" />
      </Head>
      <Box>
        <header>
          <VStack
            backgroundColor={"white"}
            backgroundImage={"/b4.svg"}
            opacity={0.8}
            height={"100%"}
            paddingY={2}
          >
            {/* <Image borderRadius={9999} src="/b1.svg" width={"150px"} /> */}
            <Box
              width={"200px"}
              height={"200px"}
              borderRadius={"full"}
              bg={"rgba(0,0, 0, 0.8)"}
            >
              <VStack mt={7}>
                <Heading textAlign={"center"} color={"white"}>
                  STORE
                </Heading>
                <Text color={"white"}>The best products</Text>
                <Navbar />
              </VStack>
            </Box>
          </VStack>
        </header>

        <main>
          <Container
            backgroundColor={"gray.100"}
            marginY={4}
            maxWidth={"container.xl"}
            boxShadow={"md"}
            borderRadius={"10"}
            padding={6}
          >
            {children}
          </Container>
        </main>
      </Box>
    </>
  );
};

export default index;
